### ISSUE TITLE
Error: Unknown authentication strategy "local.signup"

### ISSUE THREAD

**Issue by sejezara** [uzochukwueddie/footballkik#1]
I did everything the same up to "local. signup", and it gives me this error.
I wish you could help me.

Error: Unknown authentication strategy "local.signup".

at attempt (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\passport\lib\middleware\authenticate.js:186:37)
    at authenticate (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\passport\lib\middleware\authenticate.js:362:7)
    at handleReturn (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express-promise-router\lib\express-promise-router.js:24:27)
    at C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express-promise-router\lib\express-promise-router.js:56:9
    at handleReturn (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express-promise-router\lib\express-promise-router.js:24:27)
    at C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express-promise-router\lib\express-promise-router.js:56:9
    at Layer.handle [as handle_request] (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\SEJEZARA.SEJEZARA\Documents\PM\mod_proj\node_modules\express\lib\router\layer.js:95:5)

**Comment by uzochukwueddie** [comment]
It will be best if i saw your code.
Send me github link to your code

**Comment by sejezara** [comment]
https://github.com/sejezara/modproject

**Comment by sejezara** [comment]
I solved it, thank you.

**Comment by deepanshu-ahuja** [comment]
i am facing the same issue. can anyone please help

**Comment by simoubouss** [comment]
you need just add require('./passport/passport-local'); in ConfigureExpress function
